dist: xenial
language: python
python:
  - 3.7
install:
  - pip install pipenv coveralls
  - pipenv install
script:
  - python manage.py migrate
  - coverage run --source=./ --omit='*/migrations/*.py' manage.py test
after_success:
  - coveralls
