# Generated by Django 2.2 on 2019-04-30 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('comment', models.TextField(verbose_name='comment')),
                ('managers', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='managers')),
            ],
            options={
                'verbose_name': 'room',
                'verbose_name_plural': 'rooms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('end_time', models.DateTimeField(verbose_name='end time')),
                ('number_participants', models.IntegerField(verbose_name='number of participants')),
                ('validation', models.BooleanField(null=True, verbose_name='validation')),
                ('purpose_title', models.CharField(max_length=255, verbose_name='title')),
                ('purpose_body', models.TextField(verbose_name='purpose')),
                ('in_charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='in charge')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.Room', verbose_name='room')),
            ],
            options={
                'verbose_name': 'reservation',
                'verbose_name_plural': 'reservations',
                'ordering': ['start_time'],
            },
        ),
    ]
