# Generated by Django 2.2 on 2019-05-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='room',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='booking.Tag', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='room',
            name='tags',
            field=models.ManyToManyField(blank=True, to='booking.Tag', verbose_name='tags'),
        ),
    ]
