# Generated by Django 2.2.1 on 2019-05-08 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_make_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'building',
                'verbose_name_plural': 'buildings',
            },
        ),
        migrations.AlterField(
            model_name='reservation',
            name='number_participants',
            field=models.IntegerField(help_text='Approximate if unknown.', verbose_name='number of participants'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='purpose_body',
            field=models.TextField(help_text='Specify here if it is for a club.', verbose_name='purpose'),
        ),
        migrations.AlterField(
            model_name='room',
            name='comment',
            field=models.TextField(blank=True, help_text='Describe what is special about this room, such as available equipment.', null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='room',
            name='managers',
            field=models.ManyToManyField(help_text='Will manage booking for this room.', to=settings.AUTH_USER_MODEL, verbose_name='managers'),
        ),
        migrations.AddField(
            model_name='room',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Building', verbose_name='building'),
        ),
    ]
